### ISSUE TITLE
Flow editor - HVAC option not available

### ISSUE THREAD

**Issue by pimviergever** [athombv/com.nest#15]
![image](https://cloud.githubusercontent.com/assets/10696231/15157796/75fee690-16ed-11e6-9644-cd3c38975e74.png)

Firmware: 0.832
App version 1.03
Nest: 5.2.6

1st problem
Nest app removed, newly installed, app is authorized but appears gray in the settings menu:
![image](https://cloud.githubusercontent.com/assets/10696231/15157749/3ce4061a-16ed-11e6-9852-529876d44e3b.png)

2nd problem: HVAC option in the flow editor is only available when I have no nest device installed at the device section.
When removing the nest device from the device menu, the hvac option is still not available in the flow editor

log: 0A5A4DEDE8

PS: tried to reboot with the app installed: no succes. rebooted without the app installed, installed the app --> same situation: app menu is gray in the settings session and the hvac option is not available in the flow editor.

**Comment by RobinBol** [comment]
Hello Pim, thanks for reporting this issue.

1st problem: It appears there is an issue with the opacity of the settings pages in general, in the screenshot it appears the button is disabled due to the low opacity, but when you hover over it your cursor will transform into a click thingy, and if you click it will work as expected. The issue is reported internally and will be resolved.

2nd problem: There is also a general issue with these flow cards, the HVAC option is only available on the devices you have added to Homey. So it should not be present under the Nest app flow card, but when you have a thermostat installed, you can drag the thermostat device card to the "when" column and it will have a set of about three cards, among which also the HVAC option.

Please let me know if this solves it for you.

**Comment by pimviergever** [comment]
- 1st problem: It appears there is an issue with the opacity of the settings pages in general, in the screenshot it appears the button is disabled due to the low opacity, but when you hover over it your cursor will transform into a click thingy, and if you click it will work as expected. The issue is reported internally and will be resolved.  --> OK, authorisation worked, so a work around is possible, thx!

- 2nd problem: There is also a general issue with these flow cards, the HVAC option is only available on the devices you have added to Homey. So it should not be present under the Nest app flow card, but when you have a thermostat installed, you can drag the thermostat device card to the "when" column and it will have a set of about three cards, among which also the HVAC option.   --> OK, this works for me, now I can make flows with the thermostat device

- Is it possible to set the target temperate with a tag. As far as I can see, I can only set it with a slider?

**Comment by RobinBol** [comment]
Okay, thats great:) No this is not (yet) possible, the Nest app uses the default thermostat flow cards which do not support this at this moment.
