### ISSUE TITLE
Support for Nest Cams and Hello

### ISSUE THREAD

**Issue by mbnn** [athombv/com.nest#44]
Hi,

Would it be possible to include Homey support for the Nest Cams and Hello video doorbell? :)

Thanks!

**Comment by mbnn** [comment]
Hello just checking, is it possible? :)

**Comment by RobinBol** [comment]
We will be looking at adding Nest Cam support in the near future. It is very likely that the Hello cam uses the same API and therefore might be implemented too.

**Comment by HansWaldram** [comment]
Hi Robin, I will install the Nest Hello soon and would like to connect to Homey. Any idea when Homey support can be added?

**Comment by RobinBol** [comment]
Like I said earlier, we will look at it in the future, we can not say anything related to deadlines unfortunately. Since this is a device request (which we migrated from GitHub to a form recently, to keep GitHub solely focussed on bugs) I will close this issue for now and direct you to the device request form.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
